apiVersion: v1
kind: Service
metadata:
  labels:
    app: payment-mongo
  name: payment-mongo-svc
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: payment-mongo
  type: ClusterIP

