apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment-mongo
  name: payment-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-mongo
  strategy: {}
  template:
    metadata:
      labels:
        app: payment-mongo
    spec:
      containers:
      - image: mongo
        name: payment-mongo
        args: ["--dbpath","/data/db"]
        livenessProbe:
          exec:
            command:
              - mongosh
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
              - mongosh
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
              secretKeyRef:
                name: payment-database-secret-config
                key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
              secretKeyRef:
                name: payment-database-secret-config
                key: password
        volumeMounts:
        - name: "mongo-data-dir"
          mountPath: "/data/db"
      volumes:
      - name: "mongo-data-dir"
        persistentVolumeClaim:
          claimName: "mongo-data"
