apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-app
spec:
  selector:
    matchLabels:
      app: payment-app
  replicas: 1
  template:
    metadata:
      labels:
        app: payment-app
    spec:
      containers:
      - name: payment-app
        image: DOCKER_IMAGE
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
          - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /ping
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /ping
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 60
        startupProbe:
          httpGet:
            path: /ping
            port: 5000
          failureThreshold: 3
          periodSeconds: 30
        env:
          - name: MONGO_USERNAME
            valueFrom:
                secretKeyRef:
                  name: payment-database-secret-config
                  key: username
          - name: MONGO_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: payment-database-secret-config
                  key: password
          - name: MONGO_HOST
            value: payment-mongo-svc
