apiVersion: v1
kind: Service
metadata:
  name: payment-svc
  labels:
    app: payment-app
    service: payment-app
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: payment-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: delivery-payment
  labels:
    account: payment
