apiVersion: v1
kind: Service
metadata:
  name: payment-svc
  namespace: "default"
  labels:
    app: payment-app
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: payment-app
