apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentapp
spec:
  selector:
    matchLabels:
      app: paymentapp
  replicas: 1
  template:
    metadata:
      labels:
        app: paymentapp
    spec:
      containers:
      - name: paymentapp
        image: DOCKER_IMAGE
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
          - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /ping
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /ping
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 60
        startupProbe:
          httpGet:
            path: /ping
            port: 5000
          failureThreshold: 3
          periodSeconds: 30
        env:
          - name: MONGO_USERNAME
            value: VAL_MONGO_USERNAME
          - name: MONGO_PASSWORD
            value: VAL_MONGO_PASSWORD
          - name: MONGO_HOST
            value: VAL_MONGO_HOST
