apiVersion: v1
kind: Service
metadata:
  name: svcpayment
  namespace: "default"
  labels:
    app: paymentapp
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: paymentapp
